name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploying NodeJS Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        run: |
          # Install Node.js (you can specify the version you need)
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo -E apt-get install -y nodejs
          # Install project dependencies
          npm install

      - name: Build Node.js Application
        run: |
          npm run build
        continue-on-error: false # This ensures the build failure stops the workflow if it fails

      - name: deploying application to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY  }}
          HOSTNAME: ${{ secrets.SERVER_HOST  }}
          USER_NAME: ${{ secrets.SERVER_USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} bash deploy.sh
